language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --dev --prefer-source;
  - wget https://scrutinizer-ci.com/ocular.phar
  - mysql -e "create database IF NOT EXISTS zfc_user;" -uroot

script:
  - ./vendor/bin/phpunit --bootstrap=tests/bootstrap.php
  - ./vendor/bin/phpcs -n --standard=PSR2 ./src/ ./tests/

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
