<h1><?php echo $this->translate('Register'); ?></h1>

<?php
if (!$this->enableRegistration) {
    echo $this->translate('Registration is disabled');
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->partial('_form.phtml', ['form' => $form]); ?>
